/**
 * Fraud Alert Data Model
 * 
 * Stores fraud alerts generated by the stream processing pipeline
 */

const FraudAlertSchema = {
  // Alert identification
  alert_id: String,
  transaction_id: String,
  
  // Timestamp
  created_at: Date,
  
  // User and account info
  user_id: String,
  account_id: String,
  
  // Alert severity
  severity: String, // 'low', 'medium', 'high', 'critical'
  
  // Fraud score (0-100)
  fraud_score: Number,
  
  // Fraud indicators that triggered the alert
  fraud_indicators: [{
    indicator_type: String,
    description: String,
    score_contribution: Number
  }],
  
  // Transaction details (denormalized for quick access)
  transaction_summary: {
    amount: Number,
    currency: String,
    merchant_name: String,
    location: String,
    timestamp: Date
  },
  
  // Alert status
  status: String, // 'open', 'investigating', 'confirmed_fraud', 'false_positive', 'resolved'
  
  // Investigation details
  investigation: {
    assigned_to: String,
    notes: [String],
    actions_taken: [String],
    resolution_date: Date,
    resolution_notes: String
  },
  
  // Automated actions taken
  automated_actions: [{
    action_type: String, // 'block_transaction', 'flag_account', 'send_notification', 'request_verification'
    timestamp: Date,
    success: Boolean
  }],
  
  // Notification status
  notifications_sent: [{
    channel: String, // 'email', 'sms', 'push', 'webhook'
    recipient: String,
    sent_at: Date,
    delivered: Boolean
  }]
};

// Sample fraud alert
const sampleFraudAlert = {
  alert_id: "alert_abc123",
  transaction_id: "txn_1234567890",
  created_at: new Date(),
  user_id: "user_12345",
  account_id: "acc_67890",
  severity: "high",
  fraud_score: 85,
  fraud_indicators: [
    {
      indicator_type: "unusual_location",
      description: "Transaction from a country not previously used",
      score_contribution: 30
    },
    {
      indicator_type: "high_amount",
      description: "Transaction amount 5x higher than average",
      score_contribution: 25
    },
    {
      indicator_type: "velocity_check",
      description: "Multiple transactions in short time period",
      score_contribution: 30
    }
  ],
  transaction_summary: {
    amount: 2500.00,
    currency: "USD",
    merchant_name: "Unknown Merchant",
    location: "Nigeria",
    timestamp: new Date()
  },
  status: "open",
  investigation: {
    assigned_to: null,
    notes: [],
    actions_taken: [],
    resolution_date: null,
    resolution_notes: null
  },
  automated_actions: [
    {
      action_type: "block_transaction",
      timestamp: new Date(),
      success: true
    },
    {
      action_type: "send_notification",
      timestamp: new Date(),
      success: true
    }
  ],
  notifications_sent: [
    {
      channel: "email",
      recipient: "user@example.com",
      sent_at: new Date(),
      delivered: true
    }
  ]
};

module.exports = { FraudAlertSchema, sampleFraudAlert };

